### ISSUE TITLE
Search not working when not on index page

### ISSUE THREAD

**Issue by harpocrates** [sbt/sbt-paradox-material-theme#30]
This seems related to #7. Basically, whenever not on the index page, search doesn't work. There's a related JS console error `ReferenceError:` whenever not on the index page. Here's a demonstration of the problem:

When on <https://harpocrates.github.io/sample-docs-project/index.html>, I can search for "Code" and get a suggestion to go the code page:

<img width="986" alt="Screen Shot 2020-06-16 at 5 54 21 PM" src="https://user-images.githubusercontent.com/10766081/84832053-81a54c00-affa-11ea-9aad-e86f453c2d7d.png">

When on <https://harpocrates.github.io/sample-docs-project/tables.html>, no matter what I type into the search bar, nothing comes up. That includes typing in the same "Code" search. Note in the screenshot below how search bar is focused and yet the dropdown and all the other visual cues suggesting I'm searching are missing.
<img width="986" alt="Screen Shot 2020-06-16 at 5 54 35 PM" src="https://user-images.githubusercontent.com/10766081/84832131-b1545400-affa-11ea-8295-5443916ba0d5.png">

In any case, thank you for building this! 😄

**Comment by mkurz** [comment]
I cloned your repo and tried with the latest main, the problem still was there. However I found out the problem really is that you don't have a `h1` tag on each page except the index one, that's why it's working. So you need to have a main heading (h1) on each page and everything works fine. So this is not caused by this plugin.
E.g. if I change

```md
## Code
```
to
```md
# Code
```
on the code page, no error occurs and search works fine again.
