### ISSUE TITLE
Publish 0.7.0

### ISSUE THREAD

**Issue by mdedetrich** [sbt/sbt-paradox-material-theme#59]
So we can align on when to publish so we don't miss anything

**Comment by mkurz** [comment]
Almost done.
I pushed a milestone release, to check if publishing works: https://github.com/sbt/sbt-paradox-material-theme/releases/tag/v0.7.0-M1
Also before final release we want to merge:
- https://github.com/sbt/sbt-paradox-material-theme/pull/62

And maybe it makes sense to take a look at 
- https://github.com/sbt/sbt-paradox-material-theme/pull/28

which also may be a fix for
- https://github.com/sbt/sbt-paradox-material-theme/issues/30

**Comment by mkurz** [comment]
>  and only bump sbt-paradox/sbt-paradox-theme

We can not bump these two libraries to 1.x ourselves anyway, because they are hosted under the lightbend org and I do not have access to that repos. I guess you mean this repo here (sbt-paradox-material-theme).

So do I get this right, let's release 0.7.0 with paradox deps pinned to 0.9.2 (actually that is what we wanted to do anyway), branch off a 0.7.x branch from that tag, and then on main upgraded the paradox deps to 0.10.6 and release 0.8.0 (instead of 1.0.0)?

**Comment by mkurz** [comment]
@mdedetrich Everything done, all PRs merged, also [M1](https://repo1.maven.org/maven2/com/github/sbt/sbt-paradox-material-theme_2.12_1.0/) got published without problems.

You want to tag/push 0.7.0?

**Comment by mdedetrich** [comment]
> So do I get this right, let's release 0.7.0 with paradox deps pinned to 0.9.2 (actually that is what we wanted to do anyway), branch off a 0.7.x branch from that tag, and then on main upgraded the paradox deps to 0.10.6 and release 0.8.0 (instead of 1.0.0)?

Well actually I was thinking of just continuing to work on 0.7.x unless we are forced to upgrade paradox deps to 0.10.6 (or later by the time we get to it) because there isn't actually any reason to upgrade the paradox deps and doing so can cause annoyances with JDK 1.8.

**Comment by mkurz** [comment]
Hmmm... Not sure... I think you see this too much from the perspective of Pekko.
There are other projects that use this library so I am not sure it would be "fair" to hold dependency upgrades back "just" because of Pekko.
What I would do now is: releae 0.7.0 (which we do anyway), branch off 0.7.x so you can still cut 0.7.1 etc. if needed, but on master merge #66 and cut 0.8.0.
To be honest I do not expect great changes to this library currently so it's just about also having a release with all the deps up to date for other projects.

**Comment by mdedetrich** [comment]
> There are other projects that use this library so I am not sure it would be "fair" to hold dependency upgrades back "just" because of Pekko.

Unless I am missing something its not going to impact any project either way, as we speak now you can easily load sbt-paradox-material-theme with sbt-paradox/sbt-paradox-theme 0.10.6 without any issues (I can even write an sbt-scripted test to prove this).

Its the reverse i.e. downgrading the sbt-paradox/sbt-paradox-theme as is [here](https://github.com/apache/incubator-pekko-http/blob/main/project/plugins.sbt#L25-L36) due to JDK 8 that is problematic and thats what Pekko is dealing with.

**Comment by mdedetrich** [comment]
See https://github.com/sbt/sbt-paradox-material-theme/pull/67 as a demonstration

**Comment by mkurz** [comment]
Ok, then we just tag 0.7.0 and we are done I guess?

**Comment by mdedetrich** [comment]
> Ok, then we just tag 0.7.0 and we are done I guess?

Yup!

**Comment by mkurz** [comment]
Please do it, I am out of office on my phone right now

**Comment by mdedetrich** [comment]
> Please do it, I am out of office on my phone right now

Tag pushed and action triggered https://github.com/sbt/sbt-paradox-material-theme/actions/runs/7901103220 . Going to bed now, will check that its on maven tomorrow and then make release notes (if you haven't done so by the time I wake up).

**Comment by mdedetrich** [comment]
Now available on maven (see https://github.com/apache/incubator-pekko-sbt-paradox/pull/92), closing issue as completed and will make release notes
